// Code generated by "stringer -type=Type"; DO NOT EDIT

package binny

import "fmt"

const _Type_name = "NilBoolTrueBoolFalseEmptyStructVarIntInt8Int16Int32Int64VarUintUint8Uint16Uint32Uint64Float32Float64Complex64Complex128StringByteSliceStructMapSliceInterfaceBinaryGob"

var _Type_index = [...]uint8{0, 3, 11, 20, 31, 37, 41, 46, 51, 56, 63, 68, 74, 80, 86, 93, 100, 109, 119, 125, 134, 140, 143, 148, 157, 163, 166}

func (i Type) String() string {
	if i == EOV {
		return "EOV"
	}
	if i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
